// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package books

import (
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeBookHandler(db *sqlx.DB) *BookHandler {
	bookRepo := NewBookRepo(db)
	bookService := NewBookService(bookRepo)
	bookHandler := NewBookHandler(bookService)
	return bookHandler
}
