// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/jmoiron/sqlx"
	"github.com/username/mentoring_study_case/users"
)

// Injectors from wire.go:

func InitializeAuthHandler(db *sqlx.DB) *AuthHandler {
	userRepo := users.NewUserRepo(db)
	userService := users.NewUserService(userRepo)
	authService := NewAuthService(userService)
	authHandler := NewAuthHandler(authService)
	return authHandler
}
